const arrData = 
   {
        ACCOUNT_LOGIN_2016: "Account does not exist",	
        ACCOUNT_PROFIT_LOSS_2704: "Error occurred while inquiring account deposit information",	
        ACCOUNT_CASH_BALANCE_9009: "Error occurred during inquiry",	
        ACCOUNT_CASH_BALANCE_2016: "Data does not exist",	
        ACCOUNT_CASH_BALANCE_9897: "You do not  allow to do with this account",	
        ACCOUNT_CASH_BALANCE_2007: "Section value is wrong",
        ORDER_PLACE_2360: "Price cannot be higher than ceilling price.",	
        ORDER_PLACE_2361: "Price cannot be lower than floor price.",	
        ORDER_PLACE_3318: "You do not have enough cash to buy that quantity of shares.",	
        ORDER_PLACE_3373: "Là tên CK đã ngừng giao dịch",	
        ORDER_PLACE_9009: "Error occurred during inquiry (khong tim thay accountNumber)",	
        ORDER_PLACE_2322: "Order price input error",	
        ORDER_PLACE_2321: "You do not have that amount of shares to sell.",	
        ORDER_PLACE_2400: "Orders can be placed during trading hours, 09:00 to 11:30 and 13:00 to 14:45 VNT. {0}",	
        ORDER_PLACE_2387: "Không phải là ngày đặt lệnh (cuối tuần hoặc ngày lễ)",	
        ORDER_MODIFY_2341:"Không sửa được lệnh tại sàn Tp HCM",	
        ORDER_MODIFY_2514: "Order quantity input error",	
        ORDER_MODIFY_2347: "Correction order is not available",	
        ORDER_MODIFY_2513: " Không thể sửa lệnh HNX từ lệnh thường sang lô lẻ - cannot modify normal order to oddlot order",	
        ORDER_CANCEL_2349: "Cancel order is not available",	
        ORDER_ADVANCE_PLACE_2322: "Order price input error",	
        ORDER_ADVANCE_PLACE_3339: "Place advance order is not available",	
        ORDER_ADVANCE_PLACE_3340: "Place advance order is not available",	
        ORDER_ADVANCE_PLACE_3351: "Bank's information is invalid",	
        ORDER_ADVANCE_CANCEL_9009: "Error occurred during inquiry",	
        ORDER_ODDLOT_PLACE_2704: "Odlot order not allow",	
        ORDER_ODDLOT_PLACE_3351: "Bank's information is invalid",	
        ORDER_ODDLOT_PLACE_2326: "Order quantity input error",	
        ORDER_ODDLOT_PLACE_2321: "You do not have that amount of shares to sell.",	
        ORDER_ODDLOT_PLACE_2364: "Check quotation unit",	
        ORDER_ODDLOT_CANCEL_9311: "Order item does not exist",	
        ORDER_HISTORY_2016: "Data does not exist",	
        RIGHTS_AVAILABLE_2016: "Data does not exist",	
        RIGHTS_REGISTER_2716: "Đã kết thúc chi nhánh thuộc - closing of the branch is completed",	
        RIGHTS_CANCEL_2716: "Đã kết thúc chi nhánh thuộc - closing of the branch is completed",	
        LOAN_REGISTER_2119 : "Không thể xử lí được vì không có quyền của người được ủy quyền - Because agent does not have authrity, it can not be processed",	
        WITHDRAW_REQUEST_2821: "Không có quyền tác nghiệp tương ứng - You don't have permission for this operation",	
        WITHDRAW_REQUEST_7304: "Tài khoản này có sub bị nợ lớn hơn tiền mặt",	
        WITHDRAW_CANCEL_2007: "Giá trị phân loại sai - Section value is wrong",	
        TRANSFER_STOCK_2716: "Đã kết thúc chi nhánh thuộc - closing of the branch is completed",	
        TRANSFER_CASH_9009: "Phát sinh lỗi khi tra cứu - Error occurred during inquiry",	
        TRANSFER_CASH_2712: "Là lỗi khi xử lý rút tiền - Error occurred while processing payment",	
        LOGIN_CA_2016: "User không tồn tại - Sai username",	
        LOGIN_CA_9011: "Error occurred while verifing ID",	
        REGISTER_CA_9009: "User không tồn tại - Sai username",	
        // REGISTER_CA_01102: "User da ton tai",
        DR_ORDER_PLACE_2322: "Lỗi nhập giá lệnh",	
        DR_ORDER_PLACE_2326: "Lỗi nhập số lượng lệnh",	
        DR_ORDER_PLACE_6033: "Poduct code does not exist.",	
        DR_ORDER_PLACE_2361: "Error occurred since the order price is lower than lower limit",	
        DR_ORDER_PLACE_2360: "Error occurred since the order price exceeded upper limit.",	
        // DR_ORDER_PLACE_5604: "The makret is not open yet.",	
        DR_ORDER_PLACE_5605: "The market is closed.",	
        DR_ORDER_ADV_PLACE_2322: "Lỗi nhập giá lệnh",	
        DR_MODIFY_NORMAL_ORDER_2354: "Input the original order number. (để orderNumber = string)",	
        DR_MODIFY_NORMAL_ORDER_6033: "Poduct code does not exist.",	
        DR_MODIFY_NORMAL_ORDER_2361: "Lỗi giá lệnh chưa đạt tới giá sàn",	
        DR_MODIFY_NORMAL_ORDER_2006: "The account information does not exist.",	
        DR_MODIFY_NORMAL_ORDER_2360: "Error occurred since the order price exceeded upper limit.",	
        DR_CANCEL_NORMAL_ORDER_2354: "Input the original order number. (để orderNumber = string)",	
        DR_CANCEL_NORMAL_ORDER_6033: "Poduct code does not exist",	
        DR_CANCEL_NORMAL_ORDER_2006: "The account information does not exist",	
        DR_ACCOUNT_SUMMARY_2006: "Không có thông tin tài khoản",	
        DR_ACCOUNT_EQUITY_9009: "Phát sinh lỗi khi tra cứu (Sai accountNumber)",	
        DR_TRANSFER_CASH_INFO_2927: "Là tài khoản đang đóng.",	
        DR_TRANSFER_CASH_REQUEST_2821: "Không có quyền tác nghiệp tương ứng",	
        DR_TRANSFER_CASH_REQUEST_2927: "Là tài khoản đang đóng",	
        DR_TRANSFER_CASH_WITHDRAW_REQUEST_2927:"Là tài khoản đang đóng",	
        DR_TRANSFER_IM_DEPOSIT_REQUEST_2716:"Đã kết thúc chi nhánh thuộc",	
        DR_TRANSFER_CASH_WITHDRAW_INFO_2927:"Là tài khoản đang đóng",	
        DR_TRANSFER_IM_WITHDRAW_REQUEST_2716:"Đã kết thúc chi nhánh thuộc",	
        DR_ORDER_HISTORY_2010:"Input the password (do accountNumber sai hoac subNumber sai nen ko lay duoc orderPassword)",	
        DR_ORDER_ADV_PLACE_90000:"FUNCTION CHECK INPUT VALUE (do nhập sai accountNumber)",	
        DR_ORDER_ADV_PLACE_2006:"The account information does not exist",	
        DR_CANCEL_ADV_ORDER_90000:"FUNCTION CHECK INPUT VALUE (do nhập sai accountNumber)",	
        DR_CANCEL_ADV_ORDER_2006:"The account information does not exist",	
        DR_ORDER_HISTORY_2006:"The account information does not exist",	
        DR_ACCOUNT_SUMMARY_2010:"Input the password (do accountNumber sai nen ko lay duoc orderPassword)",	
        DR_ACCOUNT_BALANCE_2010:"Input the password (do accountNumber sai nen ko lay duoc orderPassword)",	
        DR_ACCOUNT_BALANCE_2006:"The account information does not exist",	
        DR_ACCOUNT_PROFIT_LOSS_2010:"Input the password (do accountNumber sai nen ko lay duoc orderPassword)",	
        DR_ACCOUNT_PROFIT_LOSS_2006:"The account information does not exist",	
        DR_ACCOUNT_PROFIT_LOSS_CUMULATIVE_2010:"The account information does not exist",	
        DR_ACCOUNT_RISK_RATIO_2010:"Input the password (do accountNumber sai nen ko lay duoc orderPassword)",	
        DR_ACCOUNT_RISK_RATIO_2006:"Không có thông tin tài khoản",	
        DR_ACCOUNT_OPEN_POSITION_2010:"Input the password (do accountNumber sai nen ko lay duoc orderPassword)",	
        DR_ACCOUNT_OPEN_POSITION_2006:"Không có thông tin tài khoản",	
        DR_HISTORY_MARGIN_CALL_2006:"Không có thông tin tài khoản",	
        DR_HISTORY_MARGIN_CALL_2010:"Input the password (do accountNumber sai nen ko lay duoc orderPassword)",	
        DR_TRANSFER_CASH_INFO_2704:"Lỗi  tra cứu thông tin tiền gửi tài khoản (Sai accountNumber or subNumber)",	
        DR_TRANSFER_IM_FEE_9009:"Phát sinh lỗi khi tra cứu\nORA-06512: at \"VN.PKG (có thể là do sai sendingBank và receivingBank)",	
        ORDER_ADVANCE_PLACE_CHECK_MARKET_STATUS:"Sai stockCode",	
        ACCOUNT_CHANGE_ORDER_PASSWORD_2716:"Đã kết thúc chi nhánh thuộc",	
        CANCEL_TRANSFER_CASH_2007:"Giá trị phân loại sai",
        UN_REGISTER_CA_01101:"Chưa đăng ký Cert",	
        LOGIN_CA_01101: "Chưa đăng ký Cert",	
        UPDATE_CA_01101: "Chưa đăng ký Cert",	
        REGISTER_CA_01102: "User đã đăng ký Cert trước đó",	
        // DR_STOP_ORDER_HISTORY_2426: "Input the inquiry type - thieu field registered",	
        DR_STOP_ORDER_HISTORY_2067: "OrderSend Type input Error - field send khong hop le",	
        ACCOUNT_CHANGE_ORDER_PASSWORD_2013:"Không có dữ liệu sửa tương ứng - sai accountNumber",	
        DR_ORDER_CANCEL_6033: "Product Code does not exist",	
        ORDER_CANCEL_3501:"Lệnh hủy bị từ chối vì có tồn tại lệnh khớp đang chờ xử lý",	
        ORDER_MODIFY_2512:"Không thể sửa lệnh HNX từ lô lẻ sang lệnh thường",
        ORDER_CANCEL_3310:"Không tồn tại số lượng chưa khớp có thể hủy",
        ORDER_MODIFY_2349:"Khong the xu ly lenh huy",
        // ORDER_MODIFY_3502: "Bạn đã đặt tổng số lệnh giống nhau liên tiếp vượt số lượng HNX cho phép",
        ORDER_MODIFY_3502: "Timeout trong khi chờ xác nhận lệnh hủy từ HOSE	",
        ORDER_CANCEL_3508: "Oder detail not change from original",
        ORDER_PLACE_2326:"Lỗi nhập số lượng lệnh",
        ORDER_PLACE_3336:"Là tên CK đã ngừng giao dịch",
        ORDER_PLACE_2391:"Không được phép mua bán cùng loại cổ phiếu",
        ORDER_PLACE_2358: "Hiện giờ không cho phép đặt lệnh",
        ORDER_MODIFY_2326: "Order quantity input error",
        ORDER_MODIFY_3508: "Order detail not change from original",
        ORDER_MODIFY_2364: "Check quotation unit",
        ORDER_CANCEL_2388: "Không xử lý được trong thời điểm cùng 1 session",
        WITHDRAW_REQUEST_2713: "Là lỗi khi đang xử lý",
        WITHDRAW_REQUEST_2732: "Lỗi nhập đối tượng phê duyệt",
        WITHDRAW_REQUEST_2831: "Đã hết thời gian yêu cầu",
        TRANSFER_STOCK_2221: "Phát sinh lỗi trong khi tra cứu số lượng khả năng xuất kho",
        TRANSFER_STOCK_9008: "Phát sinh lỗi trong khi xử lí nhập",
        ORDER_CANCEL_2400: "Để thực hiện lệnh đặt trước phiên giao dịch kế tiếp - Không thể cancel order vào thời gian này",
        ORDER_MODIFY_3120: "Order details not changed",
        ORDER_MODIFY_3311:"Không tồn tại số lượng chưa khớp có thể sửa.",
        ORDER_HISTORY_9009:"Lỗi phát sinh khi đang tra cứu",
        TRANSFER_CASH_2831: "Đã hết thời gian yêu cầu",
        DR_ACCOUNT_BALANCE_2819: "Nonexistent employee number",
        DR_ORDER_AVAILABLE_20003: 'INPUT VALUE CHECK',
        DR_ACCOUNT_SUMMARY_00902: 'Error on querry',
        // DR_STOP_ORDER_HISTORY_2426: 'Input inquiry classification',
        ORDER_ADVANCE_PLACE_9008: 'Phát sinh lỗi trong khi xử lí nhập',
        DR_HISTORY_TRADE_20003: "INPUT VALUE CHECK",
        DR_ORDER_PLACE_5604: "The market is not open yet",
        DR_CANCEL_NORMAL_ORDER_5604: "The market not open yet",
        DR_STOP_ORDER_BUY_SELL_7603:"The specified date is not business date.",
        DR_STOP_ORDER_BUY_SELL_7602:"Can not place stop order in closed session at current date",
        DR_STOP_ORDER_HISTORY_2426: 'Input inquiry classification (do thiếu field hoặc field nào đó truyền giá trị không đúng)',
        DR_STOP_ORDER_CANCEL_2363: "Input order date",
        DR_ORDER_CANCEL_9319: "Cancellation order processing is not available",
        DR_ORDER_MODIFY_5019: "There is no change in the edit order..",
        DR_ORDER_MODIFY_9318: "Correction order processing is not available",
        DR_ORDER_MODIFY_2313: "Information already contracted",
        ACCOUNT_ASSET_INFO_9903: "Màn hình này không tra cứu cho TK liên kết ngân hàng",
        DR_TRANSFER_CASH_INFO_9903: "Màn hình này không tra cứu cho TK liên kết ngân hàng",
        DR_TRANSFER_IM_FEE_3506: "Tiền giao dịch phải > tiền phí CK",
        DR_TRANSFER_CASH_WITHDRAW_INFO_9903: "Màn hình này không tra cứu cho TK liên kết ngân hàng",
        DR_STOP_ORDER_HISTORY_2305: "Check selling and buying selection",
        DR_ORDER_PLACE_5505: "The order size exceeded the order size limit",
        ORDER_PLACE_3337: "Số lượng tương ứng lớn hơn số lượng mà nước ngoài có thể mua",
        ACCOUNT_TRANSACTION_HISTORY_9101: "Thời gian tra cứu quá 300 ngày",
        DR_STOP_ORDER_MODIFY_2349: "Cancel order is not available",
        DR_ORDER_PLACE_5014: "The contract has been expired",
        DR_ORDER_MODIFY_2311: "It cannot find original order information.",
        DR_ORDER_CANCEL_2311: "It cannot find original order information.",
        DR_TRANSFER_IM_WITHDRAW_REQUEST_9008: "Phát sinh lỗi trong xử lý nhập",
        DR_ORDER_PLACE_5518: "The price change is not correct",
        DR_ORDER_PLACE_3318: "There is not enough fund available for ordering.",
        ORDER_PLACE_3351: "Thông tin ngân hàng tương ứng đã được thay đổi hoặc không tồn tại . Bạn hãy đăng nhập lại",
        ACCOUNT_LOGIN_2043: "Sai ID người sử dụng",
        DR_ORDER_MATCH_20003: "Input value check",
        TRANSFER_CASH_2711: "Là lỗi khi xử lý tiền gửi",
        DR_TRANSFER_IM_DEPOSIT_REQUEST_10006: "Hết giờ giao dịch (cut off time)",
        DR_TRANSFER_CASH_REQUEST_2831: "Đã hết thời gian yêu cầu",
        LOAN_REGISTER_2404: "Hãy nhập tổng số tiền cho vay",
        DR_TRANSFER_CASH_WITHDRAW_REQUEST_2831: "Đã hết thời gian yêu cầu.",
        DR_TRANSFER_CASH_WITHDRAW_REQUEST_2726: "Số tiền khả dụng rút bị thiếu",
        WITHDRAW_CANCEL_9812: "Phát sinh lỗi xử lí thay đổi",
        DR_ORDER_HISTORY_20003: "INPUT VALUE CHECK",
        ORDER_CANCEL_2345: "Tài khoản không thể xử lý và hạn chế nghiệp vụ",
        ORDER_MODIFY_3350: "Đây không phải là tài khoản của chi nhánh quản lí tương ứng . Xin vui lòng kiểm tra lại chi nhánh quản lí.",
        ACCOUNT_PROFIT_LOSS_2475: "Lỗi hệ thống ngân hàng",
        LOAN_AVAILABLE_9406: "Lỗi tạo nội dung dự đinh thanh toán",
        ORDER_PLACE_3376: "Mã chứng khoán không thuộc danh mục chứng khoán ký quỹ",
        WITHDRAW_REQUEST_0005: "Không có data đã nhập",
        ORDER_PLACE_2364: "Sai bước giá",
        ORDER_HISTORY_3510: "Chỉ có thể tra cứu trong khoảng thời gian 6 tháng",
        ORDER_ODDLOT_PLACE_2831: "Đã hết thời gian yêu cầu",
        DR_ORDER_ADV_PLACE_3379: "The end date should be les then the last trading date of the serie",
        ORDER_ADVANCE_CANCEL_2349: "Không thể xử lí lệnh hủy",
        DR_ORDER_ADV_PLACE_5607: "The Validity is not correct.",
        ORDER_MODIFY_3343: "Đối với lệnh của tài khoản không lưu kí ,không thể xử lí lệnh trực tuyến",
        DR_STOP_ORDER_CANCEL_2349: "The cancel order cannot be processed.",
        DR_TRANSFER_IM_DEPOSIT_REQUEST_10005: "Số dư khả dụng không đủ",
        DR_STOP_ORDER_BUY_SELL_7600: "Error occurred in Stop Order service",
        ACCOUNT_TRADING_SUMMARY_9009: "Phát sinh lỗi khi tra cứu",
        ORDER_PLACE_3501: "Khối lượng room CK ký quĩ còn lại không đủ để đặt lệnh",
        INVALID_PARAMETER: "Nhập không đúng định dạng",
        FROM_DATE_INVALID: "Ngày đặt lệnh không còn hiệu lực"
   } 
export const errorVbos = (error)=>{
    return arrData[error] || error;
}